### ISSUE TITLE
Header cuts off when scrolling to top on mobile

### ISSUE THREAD

**Issue by Whitcome** [Whit128/parallax-scrolling#1]
Using a touch screen or mobile device and scrolling up to the top very fast will cut off the header image at the top for a moment.

**Comment by bogdanfer** [comment]
can't reproduce on Android, Chrome. 
which device, OS and browser are you using?

**Comment by Whitcome** [comment]
Android 7.0 and chrome as well. Tried on a few different phones. Also does this on Edge on touch screens. Whatever color #header has will be the color it flashes to. In the demo, it's #000. It only flashes for half a second.
![capture](https://user-images.githubusercontent.com/26723989/28999439-a52c9e5c-7a0c-11e7-9907-832d8e6e55fa.PNG)

It might just be the way those browsers handle jQuery's scroll function. Not sure though.

**Comment by bogdanfer** [comment]
might be caused by the browser bar? I still can't see it on my OnePlus 3, Android 7.1.1, Chrome 59.0
if it doesnt jump or something like that, try adding `background-color: transparent;` to your #header?

**Comment by Whitcome** [comment]
Did some research - looks like it's just the way the browsers handle javascript's scroll. Not too big of a deal.
